services:
  - type: web
    name: tts-server
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 -b 0.0.0.0:$PORT tts_server:app"
    envVars:
      - key: PORT
        value: 5000
